services:
  - type: web
    name: flask-propostas-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.cnijerxppxuwfihdfmci:15k07A26l.%40@aws-0-sa-east-1.pooler.supabase.com:6543/postgres
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False